insert into student.students values (1,true,'admin@wp.pl','admin',false,'ADMINISTRATOR','$2a$10$M9pcSnWgx.QwM7qJSGrQk.KkkunoAUiuPk9KrRd7i2O5Arpo9pMeK')
-- password admin123

insert into student.students values (2,false,'bertram.lukasik@gmail.com','Bertram',false,'Łukasik','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (3,false,'efrem.kowalik@gmail.com','Efrem',false,'Kowalik','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (4,false,'natan.chojnacki@gmail.com','Natan',false,'Chojnacki','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (5,false,'kazimierz.kolodziejczyk@gmail.com','Kazimierz',false,'Kołodziejczyk','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (6,false,'eliza.adamczak@gmail.com','Eliza',false,'Adamczak','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (7,false,'walter.prus@gmail.com','Walter',false,'Prus','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (8,false,'klemens.staniszewski@gmail.com','Klemens',false,'Staniszewski','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (9,false,'ruta.zmuda@gmail.com','Ruta',false,'Żmuda','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (10,false,'antonina.rucinski@gmail.com','Antonina',false,'Ruciński','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (11,false,'jeremi.piasecki@gmail.com','Jeremi',false,'Piasecki','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (12,false,'eustracjusz.motyka@gmail.com','Eustracjusz',false,'Motyka','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (13,false,'zachariasz.niedzielski@gmail.com','Zachariasz',false,'Niedzielski','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (14,false,'gwido.kostecki@gmail.com','Gwido',false,'Kostecki','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (15,false,'gloria.kasperek@gmail.com','Gloria',false,'Kasperek','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (16,false,'ansgary.mroz@gmail.com','Ansgary',false,'Mróz','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (17,false,'chloe.kolodziejczyk@gmail.com','Chloe',false,'Kołodziejczyk','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (18,false,'jakub.janiak@gmail.com','Jakub',false,'Janiak','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (19,false,'florencja.fraczek@gmail.com','Florencja',false,'Frączek','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (20,false,'walentyna.matusiak@gmail.com','Walentyna',false,'Matusiak','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (21,false,'franciszek.zawadzki@gmail.com','Franciszek',false,'Zawadzki','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (22,false,'edgar.zawada@gmail.com','Edgar',false,'Zawada','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (23,false,'wincenty.kolodziejski@gmail.com','Wincenty',false,'Kołodziejski','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (24,false,'atanazy.szymkowiak@gmail.com','Atanazy',false,'Szymkowiak','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (25,false,'pantaleon.urbanek@gmail.com','Pantaleon',false,'Urbanek','$2a$10$CmdEtbi2sbID0S/gMzbh7uK4JmRig5ENbEt8XSDPbcX/w3KQA5GkK')
insert into student.students values (26,false,'irekfotel.g11@gmail.com','Damian',false,'Krawczyk','$2a$10$M9pcSnWgx.QwM7qJSGrQk.KkkunoAUiuPk9KrRd7i2O5Arpo9pMeK')
-- password user123

insert  into role values (1,'ROLE_ADMIN')
insert  into role values (2,'ROLE_STUDENT')

insert into student_role values (1,1)
-- 1-admin , the rest students

insert into student_role values (2,2)
insert into student_role values (3,2)
insert into student_role values (4,2)
insert into student_role values (5,2)
insert into student_role values (6,2)
insert into student_role values (7,2)
insert into student_role values (8,2)
insert into student_role values (9,2)
insert into student_role values (10,2)
insert into student_role values (11,2)
insert into student_role values (12,2)
insert into student_role values (13,2)
insert into student_role values (14,2)
insert into student_role values (15,2)
insert into student_role values (16,2)
insert into student_role values (17,2)
insert into student_role values (18,2)
insert into student_role values (19,2)
insert into student_role values (20,2)
insert into student_role values (21,2)
insert into student_role values (22,2)
insert into student_role values (23,2)
insert into student_role values (24,2)
insert into student_role values (25,2)

insert into lectures values(1,'	2019-12-10',' Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie, Sucharskiego 2','programowanie obiektowe')
insert into lectures values(2,'	2019-12-11',' Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie, Sucharskiego 2','przechowywanie i przetwarzanie danych')
insert into lectures values(3,'	2019-12-09',' Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie, Sucharskiego 2','programowanie java')
insert into lectures values(4,'	2019-12-08',' Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie, Sucharskiego 2','zaawansowane technologie programowania')
insert into lectures values(5,'	2019-12-08',' Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie, Sucharskiego 2','zaawansowane technologie programowaniaw')
insert into lectures values(6,'	2019-12-08',' Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie, Sucharskiego 2','programowanie C#')

-- admin has default pass:  'admin123' , all users have  default pass :'user123' all is bcrypted in db
